
name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main   # or "master" if your repo uses that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "vikasgautam2003"

          git clone https://huggingface.co/spaces/vikasgautam2003/Restaurant-and-Food-Menu-Generator space_repo
          rsync -av --exclude='.git' ./ space_repo/
          cd space_repo
          git add .
          git commit -m "Sync from GitHub" || echo "No changes to commit"
          git push https://USER:$HF_TOKEN@huggingface.co/spaces/vikasgautam2003/Restaurant-and-Food-Menu-Generator main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          USER: vikasgautam2003
